name = "admin"
main = "worker.js"
compatibility_date = "2024-12-01"

# Route auf deiner Zone
routes = [
  { pattern = "inpinity.online/admin*", zone_name = "inpinity.online" }
]

# ⚠️ Achte darauf, dass die CONFIG-Namespace-ID
# GENAU dieselbe ist wie bei deiner Token-API!
kv_namespaces = [
  { binding = "CONFIG", id = "a82cb91c589b4b1a8c786807a49fe5f5" },
  # Optionales Audit-Log (kann leer bleiben; nur fürs UI/Audit):
  { binding = "OPS",    id = "74e1d3dc6d84483b9454859750726be5" }
]

[vars]
# Admin-UI / Security
IP_ALLOWLIST = ""
ADMIN_REALM = "INPI Admin"
ADMIN_TOTP_PERIOD = "30"
ADMIN_TOTP_WINDOW = "1"

# Cron/HMAC (nur falls du Cron-Proxys nutzt)
CRON_BASE = "https://inpinity.online/cron"
OPS_HMAC_ALGO = "SHA-256"

# Erlaubte Keys in der Admin-Oberfläche (Whitelist)
#[vars]
# ... deine bestehenden Vars ...
CONFIG_ALLOW_ALL = "true"
CONFIG_KEYS = "*"