name = "admin"
main = "worker.js"
compatibility_date = "2024-12-01"

routes = [
  { pattern = "inpinity.online/admin*", zone_name = "inpinity.online" }
]

kv_namespaces = [
  { binding = "CONFIG", id = "a82cb91c589b4b1a8c786807a49fe5f5" }
  # Optionales Audit-Log:
  # { binding = "OPS", id = "74e1d3dc6d84483b9454859750726be5" }
]

[vars]
# Admin-UI / Security
IP_ALLOWLIST = ""
ADMIN_REALM = "INPI Admin"
ADMIN_TOTP_PERIOD = "30"
ADMIN_TOTP_WINDOW = "1"

# Cron/HMAC
CRON_BASE = "https://inpinity.online/cron"
OPS_HMAC_ALGO = "SHA-256"

# Sichtbare/erlaubte Config-Keys im Admin
CONFIG_KEYS = "INPI_MINT,presale_state,tge_ts,presale_price_usdc,public_price_usdc,presale_target_usdc,cap_per_wallet_usdc,presale_deposit_usdc,nft_gate_enabled,gate_collection,nft_gate_collection,public_mint_enabled,public_mint_price_usdc,public_mint_fee_bps,public_mint_fee_dest,sale_nft_quota_bps,sale_public_quota_bps,sale_overflow_action,lp_split_bps,lp_bucket_usdc,lp_lock_initial_days,lp_lock_rolling_days,staking_total_inpi,staking_fee_bps,staking_start_ts,staking_end_ts,buyback_enabled,buyback_min_usdc,buyback_twap_slices,buyback_cooldown_min,buyback_split_burn_bps,buyback_split_lp_bps,floor_enabled,floor_min_usdc_per_inpi,floor_window_min,floor_daily_cap_usdc,cb_enabled,cb_drop_pct_1h,cb_vol_mult,cb_cooldown_min,creator_usdc_stream_monthly_usdc,creator_usdc_stream_months,creator_usdc_stream_next_ts,creator_inpi_stream_bps_per_month,creator_inpi_stream_months,creator_inpi_stream_next_ts,supply_total,governance_multisig,timelock_seconds,project_uri,whitepaper_sha256,twap_enabled,dist_presale_bps,dist_dex_liquidity_bps,dist_staking_bps,dist_ecosystem_bps,dist_treasury_bps,dist_team_bps,dist_airdrop_nft_bps,dist_buyback_reserve_bps"