name = "admin"
main = "worker.js"
compatibility_date = "2024-12-01"

routes = [
  { pattern = "inpinity.online/admin*", zone_name = "inpinity.online" }
]

kv_namespaces = [
  { binding = "CONFIG",  id = "a82cb91c589b4b1a8c786807a49fe5f5" }
]

# setze Benutzer/Passwort als Secrets (siehe unten)