name = "admin"
main = "worker.js"
compatibility_date = "2024-12-01"

routes = [
  { pattern = "inpinity.online/admin*", zone_name = "inpinity.online" }
]

kv_namespaces = [
  { binding = "CONFIG", id = "a82cb91c589b4b1a8c786807a49fe5f5" },
  { binding = "OPS",    id = "74e1d3dc6d84483b9454859750726be5" }
]

[vars]
IP_ALLOWLIST = ""                   # optional IP-Whitelist (leer = aus)
ADMIN_REALM = "INPI Admin"
ADMIN_TOTP_PERIOD = "30"            # falls du OTP nachrüsten willst
ADMIN_TOTP_WINDOW = "1"
CRON_BASE = "https://inpinity.online/cron"
OPS_HMAC_ALGO = "SHA-256"