name = "admin"
main = "worker.js"
compatibility_date = "2024-12-01"

routes = [
  { pattern = "inpinity.online/admin*", zone_name = "inpinity.online" },
  { pattern = "inpinity.online/public/app-cfg", zone_name = "inpinity.online" }
]

kv_namespaces = [
  { binding = "CONFIG", id = "a82cb91c589b4b1a8c786807a49fe5f5" }
]

[vars]
ADMIN_REALM = "INPI Admin"
IP_ALLOWLIST = ""     # optional, z.B. "1.2.3.4, 5.6.7.8"
OPS_HMAC_ALGO = "SHA-256"
# cf-workers/admin/wrangler.toml
[vars]
# cf-workers/admin/wrangler.toml
[vars]
CONFIG_KEYS = "INPI_MINT,buyback_cooldown_min,buyback_enabled,buyback_min_usdc,buyback_split_burn_bps,buyback_split_lp_bps,buyback_twap_slices,cap_per_wallet_usdc,cb_cooldown_min,cb_drop_pct_1h,cb_enabled,cb_vol_mult,creator_inpi_stream_bps_per_month,creator_inpi_stream_months,creator_inpi_stream_next_ts,creator_pubkey,creator_usdc_stream_monthly_usdc,creator_usdc_stream_months,creator_usdc_stream_next_ts,deposit_owner,dist_airdrop_nft_bps,dist_buyback_reserve_bps,dist_dex_liquidity_bps,dist_ecosystem_bps,dist_presale_bps,dist_staking_bps,dist_team_bps,dist_treasury_bps,early_claim_enabled,early_claim_fee_bps,early_claim_fee_dest,early_fee_usdc_ata,floor_daily_cap_usdc,floor_enabled,floor_min_usdc_per_inpi,floor_window_min,game_sink_fee_bps,game_sink_mode,gate_collection,gate_mint,governance_multisig,lp_bucket_usdc,lp_lock_initial_days,lp_lock_rolling_days,lp_split_bps,nft_gate_collection,nft_gate_enabled,presale_cap_nft_inpi,presale_cap_public_inpi,presale_cap_total_inpi,presale_deposit_usdc,presale_max_usdc,presale_min_usdc,presale_price_usdc,presale_state,presale_target_usdc,project_uri,public_mint_enabled,public_mint_fee_bps,public_mint_fee_dest,public_mint_price_usdc,public_price_usdc,public_rpc_url,sale_nft_quota_bps,sale_overflow_action,sale_public_quota_bps,staking_end_ts,staking_fee_bps,staking_start_ts,staking_total_inpi,supply_total,tge_ts,tier_nft_price_usdc,tier_public_price_usdc,timelock_seconds,token:allocations,twap_enabled,wait_bonus_bps,whitepaper_sha256,gate_discount_bps,early_flat_usdc,airdrop_bonus_bps"# Setze diese als Secrets:


# wrangler secret put ADMIN_USER
# wrangler secret put ADMIN_PASS