name = "admin"
main = "worker.js"
compatibility_date = "2024-12-01"

routes = [
  { pattern = "inpinity.online/admin*", zone_name = "inpinity.online" },
  { pattern = "inpinity.online/public/app-cfg", zone_name = "inpinity.online" }
]

kv_namespaces = [
  { binding = "CONFIG", id = "a82cb91c589b4b1a8c786807a49fe5f5" }
]

[vars]
ADMIN_REALM = "INPI Admin"
IP_ALLOWLIST = ""     # optional, z.B. "1.2.3.4, 5.6.7.8"
OPS_HMAC_ALGO = "SHA-256"
CONFIG_KEYS = ""
# Setze diese als Secrets:
# wrangler secret put ADMIN_USER
# wrangler secret put ADMIN_PASS