# ============================================
# INPI Admin Worker – Whitelist-frei
# - Hauptziel: Keys im KV "INPI_CONFIG" lesen/schreiben
# - UI:        /admin
# - Public:    /public/app-cfg (vom Frontend nutzbar)
# ============================================

name = "admin"
main = "worker.js"
compatibility_date = "2024-12-01"

# Routen für Admin-UI und die öffentliche App-Konfig
routes = [
  { pattern = "inpinity.online/admin*",   zone_name = "inpinity.online" },
  { pattern = "inpinity.online/public/*", zone_name = "inpinity.online" }
]

kv_namespaces = [
  { binding = "CONFIG", id = "a82cb91c589b4b1a8c786807a49fe5f5" }
]

[vars]
# Sichtbarer Name in der Basic-Auth-Aufforderung
ADMIN_REALM   = "INPI Admin"

# Optional: IP-Whitelist (leer = alle IPs erlaubt)
IP_ALLOWLIST  = ""

# Nur Header/Meta-Kram für das UI; hat keinen Einfluss auf /config/*
CRON_BASE     = "https://inpinity.online/cron"
OPS_HMAC_ALGO = "SHA-256"

