name = "proxy-token-pages
proxy-token-pages

main = "worker.js"
compatibility_date = "2024-12-01"

routes = [
  { pattern = "inpinity.online/api/token/*", zone_name = "inpinity.online" }
]

kv_namespaces = [
  { binding = "CONFIG",  id = "<ID_INPI_CONFIG>"  },
  { binding = "PRESALE", id = "<ID_INPI_PRESALE>" },
  { binding = "CLAIMS",  id = "<ID_INPI_CLAIMS>"  }
]