name = "cron-jobs"
main = "worker.js"
compatibility_date = "2024-12-01"

# Zwei Crons:
triggers = { crons = ["*/30 * * * *", "*/10 * * * *"] }

routes = [
  { pattern = "inpinity.online/cron/*", zone_name = "inpinity.online" }
]

kv_namespaces = [
  { binding = "CONFIG", id = "a82cb91c589b4b1a8c786807a49fe5f5" },  # INPI_CONFIG
  { binding = "OPS",    id = "74e1d3dc6d84483b9454859750726be5" }                       # hier deine neue ID eintragen
]