name = "cron-jobs"
main = "worker.js"
compatibility_date = "2024-12-01"

triggers = { crons = ["*/30 * * * *", "*/10 * * * *"] }

routes = [
  { pattern = "inpinity.online/cron/*", zone_name = "inpinity.online" }
]

kv_namespaces = [
  { binding = "CONFIG",  id = "a82cb91c589b4b1a8c786807a49fe5f5" },
  { binding = "OPS",     id = "74e1d3dc6d84483b9454859750726be5" },
  { binding = "PRESALE", id = "c7fe71ba6bd54e2a9ce76ed9c726a75d" }
]

[vars]
IP_ALLOWLIST = ""        # optional: HTTP-Zugriff auf /cron/* einschränken
OPS_HMAC_ALGO = "SHA-256"
RECONCILE_BATCH = "200"
WEBHOOK_URL = ""
# Für gesicherte Bot-Calls:
# wrangler secret put OPS_API_KEY